### ISSUE TITLE
Please could you share the info you used for base algorithm programming

### ISSUE THREAD

**Issue by ealcober** [alermi/JUCE-HighPass#1]
Hello Alermi. Just studying your hpfilter and trying to find where did you find the base algorithm. could you please inform me about it? best regards, thank you very much @alermi

**Comment by alermi** [comment]
My professor at the time provided me with the 4 pole lowpass algorithm. I then turned it into a highpass by subtracting the filtered signal from the input. I am not sure where it is originally from.
